### ISSUE TITLE
nonparam anova2onerm missing nPermTotal?

### ISSUE THREAD

**Issue by adrianrivadulla** [0todd0000/spm1d#274] opened 2023-12-27 13:40 UTC
Hi, I'm trying to run a non parametric 2-way ANOVA with one RM factor. following the example in [spm1d/examples/nonparam/1d/ex_anova2onerm.py](url), I get the following error:

TypeError: _check_iterations() missing 1 required positional argument: 'nPermTotal'

My script used to work a year or two ago so I don't know if the error could be version dependent?  I am currently using the latest version of spm1d in Python (0.4.22). I've tried the example provided in the package and I get the same error. The problem is I can't remember what version I had when it used to work and my environment file got corrupted a few months ago so I can't easily trace it back.

Is this a bug? Can I set the nPermTotal somewhere and what should I set it to?

Thank you

**Comment by 0todd0000** [comment] 2023-12-28 05:31
Thank you very much for reporting this problem!  It is indeed a version-dependent software bug, and after checking into it I found that this bug affected several nonparametric procedures. So thank you indeed for reporting it!

It seems that the cause was a recent update to the `iteration` parameter checks;  I thought that these changes had been propagated to all procedures but apparently not!

Regardless, the bug is now fixed, and all nonparametric example scripts appear to be working fine.

Please update to the new version (0.4.23) which has been pushed to [pypi](https://pypi.org/project/spm1d/). If you use pypi you should be able to update with: 

```
pip install spm1d --upgrade
```

**Closed** 2024-04-23 01:24 UTC
