### ISSUE TITLE
Statistical tests (main) ERROR - 'module' object has no attribute 'gam'

### ISSUE THREAD

**Issue by AurelieS** [0todd0000/spm1d#8] opened 2015-04-23 15:59 UTC
Hi,

I am new to both Python and SPM, and I am following the tutorial on your website http://www.spm1d.org/doc/Examples_stats_basic.html with the final objective to use SPM to compare EMG signals. 

However, when trying to launch "./spm1d/examples/ex03_00_ttest.py" (or any statistical test with the function "inference"), I am encountering the following error:
"""
 File "C:\Anaconda\spm1d\_prob.py", line 128, in prob_rft
 G = np.sqrt(pi)/(stats.distributions.gam(0.5*np.arange(1,D+1)))

AttributeError: 'module' object has no attribute 'gam'
"""

I am using Python 2.7.8 with Spyder 2.3.4.

Thanks a lot in advance,

Sincerely,
Aurelie Sarcher

**Comment by 0todd0000** [comment] 2015-04-23 19:21
Hi Aurelie,
Thank you for reporting this issue.
From the error message it sounds like you're using a previous version of the software (version 0.1).  To check, try:

```python
>>>  import spm1d
>>>  print spm1d.__version__
```

If the version number is not 0.2.xxxx, then please try downloading and running the most recent version. 

The error refers to an old SciPy interface which no longer exists. If you'd like to confirm that this is indeed the problem, try the following:

```python
>>>  import scipy.stats.distributions.gam
```
That should generate the following error:

```python
ImportError: No module named gam
```


Please let me know if this solves the problem.

Best,
Todd

**Comment by AurelieS** [comment] 2015-04-23 19:54
Thank you very much for your response.

I am encountering the exact same issue on my MacOS equipped with Python 2.7.9 and Spyder 2.3.2 (previous was with Windows).

I checked the SPM1D version for both the computers and it is the "0.2 (2014/05/01)". 

I also checked my scipy version, and it is a recent one, "0.14.0".

And indeed 
```python
>>>  import scipy.stats.distributions.gam
```
Does generate the following error:
```python
ImportError: No module named gam
```

Best regards,
Aurélie

**Comment by 0todd0000** [comment] 2015-04-23 23:50
Hi Aurelie,

This is odd.

(1)  The line causing the problem (copied immediately below) exists in version 0.1 but not in version 0.2.  Is it possible that version 0.1 is also installed?

```python
G = np.sqrt(pi)/(stats.distributions.gam(0.5*np.arange(1,D+1)))
```



(2) The **spm1d** package must reside in a folder called "spm1d", but from the error message it appears that package files reside in `C:\Anaconda\`.  To properly import **spm1d** the **spm1d** folder must be located in a folder that is on the Python path. Thus if `C:\Anaconda\` is on the Python path, then there should be a folder called `C:\Anaconda\spm1d` that contains an `__init__.py` file and all other **spm1d** modules.


In case the comments above do not help, could you please copy and paste the output of the following commands into your next response?

```python
>>> import spm1d
>>> print spm1d
```
That should generate something like this:

```python
<module 'spm1d' from '/Users/USERNAME/Python/spm1d/__init__.pyc'>
```

Cheers,

Todd

**Comment by AurelieS** [comment] 2015-04-24 05:44
1) Actually, if you download the package currently available at http://www.spm1d.org/Downloads.html, you will see that this line indeed exists in the file spm1d/_prob.py 

It was the first time I downloaded the package SPM1D, so I don't think it is possible that I also have an old version hidden somewhere.

2) The spm1d package indeed resides in a folder called "spm1d".

input:
```python
>>> import spm1d
>>> print spm1d
```

output:
```python
<module 'spm1d' from '/Users/Aurelie/anaconda/lib/python2.7/spm1d/__init__.pyc'>
```

I tried moving the spm1d folder (for example in my Desktop), and appending the new folder to the Python path but I still got the same error..

It is possible the version uploaded on the website is not the right one ? 

Thanks and regards,
Aurelie

**Comment by 0todd0000** [comment] 2015-04-24 07:54
Hi Aurelie,

You're absolutely right, file should indeed be`\spm1d\_prob.py`.  Since the error message contains  `C:\Anaconda\spm1d_prob.py` it appears as if there's a file called `.\spm1d_prob.py`, but this could just be a display error.  Anyway, the package import does work, so the source of the problem is clearly elsewhere.

I just discovered something extremely odd about spm1d.org:
If I download **spm1d.02.zip** using Firefox, the most current version is downloaded (version 0.2.0006). However, if I use Safari, the version you mention (version 0.2) is downloaded.  This happens even after refreshing and relaunching Safari, and it also happens from other computers.

Did you by chance use Safari to download the software?
If so could you try using Firefox or another browser?
Please check the `./spm1d/__init__.py file` for the version number.

Todd

**Comment by AurelieS** [comment] 2015-04-24 08:16
With my MacOS I used Safari, but with the Windows I used Firefox 34.0.5 and for both I got the 2.0 version.

I tried downloading the package with Internet Explorer 9.0 and it works !! I downloaded the right version '0.2.0006 (2014/07/09)' and all the examples work... For once, Internet Explorer is better than Firefox and Safari !! very strange indeed ;)

Thank you very much for your help, I look forward to try and use SPM for my EMG signals !

Best regards,
Aurelie

**Comment by 0todd0000** [comment] 2015-04-24 08:30
Hi Aurelie,
I'm glad it's working.  That downloading bug must originate in the spm1d.org server.   I'll try to isolate and fix the problem.

Please note that version 0.3 of the software will be available later this year.  For that version I plan to transfer everything to a more standard version control system, likely here on GitHub. That should fix most downloading and updating problems.

Thank you very much for reporting this bug.  I'll close this issue for now, but please don't hesitate to generate a new issue if anything comes up.

Cheers,
Todd

**Closed by 0todd0000** 2015-04-24 08:30 UTC
